spring:
  application:
    name: system-service
  cloud:
    nacos:
      config:
        server-addr: 192.168.226.128:8848
        file-extension: yml
      discovery:
        server-addr: 192.168.226.128:8848
    sentinel:
      transport:
        port: 8720
        dashboard: 192.168.226.128:8060
  boot:
    admin:
      client:
        url: http://localhost:8070
#        username: admin
#        password: admin

server:
  port: 8082

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: ALWAYS